server:
  port: 8080

spring:
  datasource:
    url: jdbc:sqlite:${SQLITE_DB_PATH:/home/database.db}
    driver-class-name: org.sqlite.JDBC
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    open-in-view: false

# JWT設定
jwt:
  secret: ${DB_PASSWORD}